server.servlet.contextPath=/random
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:scaling-service.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
spring.rsocket.server.port=7000
spring.rsocket.server.transport=tcp
spring.rsocket.server.ssl.enabled=true
spring.rsocket.server.ssl.key-store=classpath:scaling-service.p12
spring.rsocket.server.ssl.key-store-password=changeit
spring.rsocket.server.ssl.key-store-type=PKCS12
